#!/usr/bin/env node
// design-tokens/gen.mjs — codegen for the shared design-token + status SSOT.
//
// Reads the two source-of-truth JSON files (tokens.json, status.json) and emits
// four generated artifacts consumed by the two separate frontends:
//
//   web/ (fixed dark-theme Tailwind app)
//     - web/tailwind.preset.cjs        theme.extend colors/font/radius from tokens
//     - web/src/status.generated.ts    STATUS_CONFIG / UNKNOWN_CONFIG (Tailwind classes)
//
//   cao_mcp_apps/ (host-themed, JIT-free, single-file in-host app)
//     - cao_mcp_apps/src/shared/tokens.generated.css   :root fallback == tokens
//     - cao_mcp_apps/src/shared/status.generated.ts     status -> {label,role,pulse}
//
// This is CODEGEN, not a runtime dependency: cao_mcp_apps gains zero runtime deps
// (protecting the JIT-free + size budgets) and web stays Tailwind-native. A CI
// parity guard re-runs this with `--check`, which regenerates in memory and fails
// (exit 1) if any committed artifact is stale.
//
// Usage:
//   node design-tokens/gen.mjs            # write all artifacts
//   node design-tokens/gen.mjs --check    # verify artifacts are up to date

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..");

const tokens = JSON.parse(readFileSync(resolve(HERE, "tokens.json"), "utf8"));
const status = JSON.parse(readFileSync(resolve(HERE, "status.json"), "utf8"));

const HEADER_TS =
  "// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.\n" +
  "// Edit design-tokens/tokens.json or design-tokens/status.json, then run\n" +
  "// `node design-tokens/gen.mjs`. CI (`gen.mjs --check`) fails on drift.\n";

const HEADER_HASH =
  "/* @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.\n" +
  "   Edit design-tokens/tokens.json, then run `node design-tokens/gen.mjs`.\n" +
  "   CI (`gen.mjs --check`) fails on drift. */\n";

// Map each semantic role -> the Tailwind color key (web) and the CSS custom
// property (cao_mcp_apps). These two names are the only role wiring; everything
// else flows from color.role in tokens.json.
const ROLE_ORDER = ["success", "info", "accent", "warning", "danger", "neutral"];

function lightDark(pair) {
  return `light-dark(${pair.light}, ${pair.dark})`;
}

// ---------------------------------------------------------------------------
// web/tailwind.preset.cjs
// ---------------------------------------------------------------------------
function genTailwindPreset() {
  const role = tokens.color.role;
  // web is a fixed dark theme: status colors use the .dark variant.
  const caoColors = ROLE_ORDER.map(
    (r) => `      "${r}": "${role[r].dark}",`,
  ).join("\n");

  return (
    "// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.\n" +
    "// Edit design-tokens/tokens.json, then run `node design-tokens/gen.mjs`.\n" +
    "// CI (`gen.mjs --check`) fails on drift.\n" +
    "//\n" +
    "// Tailwind preset: the web app's theme is token-derived. Semantic status\n" +
    "// colors live under the `cao-*` color family (e.g. `text-cao-success`).\n" +
    "/** @type {import('tailwindcss').Config} */\n" +
    "module.exports = {\n" +
    "  theme: {\n" +
    "    extend: {\n" +
    "      colors: {\n" +
    "        cao: {\n" +
    caoColors +
    "\n" +
    "        },\n" +
    "      },\n" +
    `      fontFamily: {\n` +
    `        sans: ${JSON.stringify(tokens.typography.fontSans.split(", "))},\n` +
    "      },\n" +
    "      fontWeight: {\n" +
    `        semibold: "${tokens.typography.fontWeightSemibold}",\n` +
    "      },\n" +
    "      borderRadius: {\n" +
    `        md: "${tokens.radius.md}",\n` +
    `        full: "${tokens.radius.full}",\n` +
    "      },\n" +
    "    },\n" +
    "  },\n" +
    "};\n"
  );
}

// ---------------------------------------------------------------------------
// web/src/status.generated.ts
// ---------------------------------------------------------------------------
function genWebStatus() {
  const entries = Object.entries(status.statuses);
  const known = entries.filter(([k]) => k !== "unknown");
  const unknown = status.statuses.unknown;

  const configEntries = known
    .map(([key, s]) => {
      const role = s.semanticRole;
      const lines = [
        `  ${key.toUpperCase()}: {`,
        `    label: ${JSON.stringify(s.label)},`,
        `    dotClass: "bg-cao-${role}",`,
        `    bgClass: "bg-cao-${role}/10",`,
        `    textClass: "text-cao-${role}",`,
      ];
      if (s.pulse) lines.push("    pulse: true,");
      lines.push("  },");
      return lines.join("\n");
    })
    .join("\n");

  return (
    HEADER_TS +
    "//\n" +
    "// web StatusBadge config. Keys are UPPERCASE terminal statuses; classes are\n" +
    "// Tailwind utilities resolved against the `cao-*` colors in tailwind.preset.cjs.\n" +
    "\n" +
    "export interface StatusStyle {\n" +
    "  label: string;\n" +
    "  dotClass: string;\n" +
    "  bgClass: string;\n" +
    "  textClass: string;\n" +
    "  pulse?: boolean;\n" +
    "}\n" +
    "\n" +
    "export const STATUS_CONFIG: Record<string, StatusStyle> = {\n" +
    configEntries +
    "\n};\n" +
    "\n" +
    "export const UNKNOWN_CONFIG: StatusStyle = {\n" +
    `  label: ${JSON.stringify(unknown.label)},\n` +
    `  dotClass: "bg-cao-${unknown.semanticRole}",\n` +
    `  bgClass: "bg-cao-${unknown.semanticRole}/10",\n` +
    `  textClass: "text-cao-${unknown.semanticRole}",\n` +
    "};\n"
  );
}

// ---------------------------------------------------------------------------
// cao_mcp_apps/src/shared/tokens.generated.css
// ---------------------------------------------------------------------------
function genTokensCss() {
  const c = tokens.color;
  const lines = [];
  lines.push(HEADER_HASH);
  lines.push("");
  lines.push("/* :root fallback layer. Host CSS variables (SEP-1865 theming)");
  lines.push("   override these at runtime — these are defaults only. */");
  lines.push(":root {");
  // Chrome variables (consumed across styles.css).
  lines.push("  /* chrome */");
  lines.push(`  --color-background-primary: ${lightDark(c.background.primary)};`);
  lines.push(`  --color-background-secondary: ${lightDark(c.background.secondary)};`);
  lines.push(`  --color-background-danger: ${lightDark(c.background.danger)};`);
  lines.push(`  --color-background-info: ${lightDark(c.background.info)};`);
  lines.push(`  --color-text-primary: ${lightDark(c.text.primary)};`);
  lines.push(`  --color-text-secondary: ${lightDark(c.text.secondary)};`);
  lines.push(`  --color-text-danger: ${lightDark(c.text.danger)};`);
  lines.push(`  --color-text-info: ${lightDark(c.text.info)};`);
  lines.push(`  --color-border-primary: ${lightDark(c.border.primary)};`);
  lines.push(`  --color-border-info: ${lightDark(c.border.info)};`);
  lines.push(`  --font-sans: ${tokens.typography.fontSans};`);
  lines.push(`  --font-weight-semibold: ${tokens.typography.fontWeightSemibold};`);
  lines.push(`  --border-radius-md: ${tokens.radius.md};`);
  lines.push(`  --border-radius-full: ${tokens.radius.full};`);
  // Status semantic-role colors (host-overridable).
  lines.push("  /* status semantic roles */");
  for (const r of ROLE_ORDER) {
    lines.push(`  --cao-status-${r}: ${lightDark(c.role[r])};`);
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// cao_mcp_apps/src/shared/status.generated.ts
// ---------------------------------------------------------------------------
function genMcpStatus() {
  const entries = Object.entries(status.statuses);
  const body = entries
    .map(([key, s]) => {
      return (
        `  ${JSON.stringify(key)}: { ` +
        `label: ${JSON.stringify(s.label)}, ` +
        `semanticRole: ${JSON.stringify(s.semanticRole)}, ` +
        `pulse: ${s.pulse ? "true" : "false"} },`
      );
    })
    .join("\n");

  return (
    HEADER_TS +
    "//\n" +
    "// cao_mcp_apps status semantics. Keys are lowercase terminal statuses. The\n" +
    "// `semanticRole` resolves to the `--cao-status-<role>` CSS variable (defined\n" +
    "// in tokens.generated.css, host-overridable). `pulse` drives the animation.\n" +
    "\n" +
    'export type SemanticRole =\n' +
    ROLE_ORDER.map((r) => `  | ${JSON.stringify(r)}`).join("\n") +
    ";\n" +
    "\n" +
    "export interface StatusSemantics {\n" +
    "  label: string;\n" +
    "  semanticRole: SemanticRole;\n" +
    "  pulse: boolean;\n" +
    "}\n" +
    "\n" +
    "export const STATUS: Record<string, StatusSemantics> = {\n" +
    body +
    "\n};\n" +
    "\n" +
    "/** The canonical set of known status keys (render/validation order). */\n" +
    "export const KNOWN_STATUSES: readonly string[] = Object.keys(STATUS);\n"
  );
}

// ---------------------------------------------------------------------------
// driver
// ---------------------------------------------------------------------------
const ARTIFACTS = [
  { path: resolve(REPO, "web/tailwind.preset.cjs"), content: genTailwindPreset() },
  { path: resolve(REPO, "web/src/status.generated.ts"), content: genWebStatus() },
  {
    path: resolve(REPO, "cao_mcp_apps/src/shared/tokens.generated.css"),
    content: genTokensCss(),
  },
  {
    path: resolve(REPO, "cao_mcp_apps/src/shared/status.generated.ts"),
    content: genMcpStatus(),
  },
];

const check = process.argv.includes("--check");
let stale = 0;

for (const { path, content } of ARTIFACTS) {
  const rel = relative(REPO, path);
  if (check) {
    let current = null;
    try {
      current = readFileSync(path, "utf8");
    } catch {
      current = null;
    }
    if (current !== content) {
      stale += 1;
      console.error(`STALE: ${rel}`);
    } else {
      console.log(`ok: ${rel}`);
    }
  } else {
    writeFileSync(path, content);
    console.log(`wrote: ${rel}`);
  }
}

if (check && stale > 0) {
  console.error(
    `\ngen.mjs --check: ${stale} stale artifact(s). Run \`node design-tokens/gen.mjs\` and commit.`,
  );
  process.exit(1);
}

console.log(
  check
    ? "gen.mjs --check: all artifacts up to date."
    : `gen.mjs: wrote ${ARTIFACTS.length} artifact(s).`,
);
