// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.
// Edit design-tokens/tokens.json or design-tokens/status.json, then run
// `node design-tokens/gen.mjs`. CI (`gen.mjs --check`) fails on drift.
//
// cao_mcp_apps status semantics. Keys are lowercase terminal statuses. The
// `semanticRole` resolves to the `--cao-status-<role>` CSS variable (defined
// in tokens.generated.css, host-overridable). `pulse` drives the animation.

export type SemanticRole =
  | "success"
  | "info"
  | "accent"
  | "warning"
  | "danger"
  | "neutral";

export interface StatusSemantics {
  label: string;
  semanticRole: SemanticRole;
  pulse: boolean;
}

export const STATUS: Record<string, StatusSemantics> = {
  "idle": { label: "Idle", semanticRole: "success", pulse: false },
  "processing": { label: "Processing", semanticRole: "info", pulse: true },
  "completed": { label: "Completed", semanticRole: "accent", pulse: false },
  "waiting_user_answer": { label: "Awaiting Input", semanticRole: "warning", pulse: false },
  "error": { label: "Error", semanticRole: "danger", pulse: false },
  "stopped": { label: "Stopped", semanticRole: "neutral", pulse: false },
  "unknown": { label: "Unknown", semanticRole: "neutral", pulse: false },
};

/** The canonical set of known status keys (render/validation order). */
export const KNOWN_STATUSES: readonly string[] = Object.keys(STATUS);
