// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.
// Edit design-tokens/tokens.json or design-tokens/status.json, then run
// `node design-tokens/gen.mjs`. CI (`gen.mjs --check`) fails on drift.
//
// web StatusBadge config. Keys are UPPERCASE terminal statuses; classes are
// Tailwind utilities resolved against the `cao-*` colors in tailwind.preset.cjs.

export interface StatusStyle {
  label: string;
  dotClass: string;
  bgClass: string;
  textClass: string;
  pulse?: boolean;
}

export const STATUS_CONFIG: Record<string, StatusStyle> = {
  IDLE: {
    label: "Idle",
    dotClass: "bg-cao-success",
    bgClass: "bg-cao-success/10",
    textClass: "text-cao-success",
  },
  PROCESSING: {
    label: "Processing",
    dotClass: "bg-cao-info",
    bgClass: "bg-cao-info/10",
    textClass: "text-cao-info",
    pulse: true,
  },
  COMPLETED: {
    label: "Completed",
    dotClass: "bg-cao-accent",
    bgClass: "bg-cao-accent/10",
    textClass: "text-cao-accent",
  },
  WAITING_USER_ANSWER: {
    label: "Awaiting Input",
    dotClass: "bg-cao-warning",
    bgClass: "bg-cao-warning/10",
    textClass: "text-cao-warning",
  },
  ERROR: {
    label: "Error",
    dotClass: "bg-cao-danger",
    bgClass: "bg-cao-danger/10",
    textClass: "text-cao-danger",
  },
  STOPPED: {
    label: "Stopped",
    dotClass: "bg-cao-neutral",
    bgClass: "bg-cao-neutral/10",
    textClass: "text-cao-neutral",
  },
};

export const UNKNOWN_CONFIG: StatusStyle = {
  label: "Unknown",
  dotClass: "bg-cao-neutral",
  bgClass: "bg-cao-neutral/10",
  textClass: "text-cao-neutral",
};
