// @generated by design-tokens/gen.mjs — DO NOT EDIT BY HAND.
// Edit design-tokens/tokens.json, then run `node design-tokens/gen.mjs`.
// CI (`gen.mjs --check`) fails on drift.
//
// Tailwind preset: the web app's theme is token-derived. Semantic status
// colors live under the `cao-*` color family (e.g. `text-cao-success`).
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        cao: {
      "success": "#34d399",
      "info": "#60a5fa",
      "accent": "#c084fc",
      "warning": "#fbbf24",
      "danger": "#f87171",
      "neutral": "#a3a3a3",
        },
      },
      fontFamily: {
        sans: ["system-ui","-apple-system","sans-serif"],
      },
      fontWeight: {
        semibold: "600",
      },
      borderRadius: {
        md: "8px",
        full: "999px",
      },
    },
  },
};
